MANUAL_EXECUTION = "Manual execution"
AUTOMATIC_EXECUTION = "Automatic Execution"

X_AXIS_MIN_LENGTH = 15
PLOT_INITIAL_WIDTH = 8.5
PLOT_INITIAL_HEIGHT = 5

GUI_MAIN_COLOR = "#95b88d"
GUI_TAB_COLOR = "#76966f"